baseURL = 'https://jdillard.github.io/murder-mystery/'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'Whatcom Murder Mystery'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
